# Generated by Django 4.1 on 2022-08-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_usersettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.UUIDField()),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=200, null=True)),
                ("last_name", models.CharField(max_length=200, null=True)),
                ("user_id", models.PositiveIntegerField(null=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("token_life", models.PositiveIntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
