# Generated by Django 4.1 on 2022-08-09 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rpi", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="raspberrypimodel",
            old_name="model",
            new_name="name",
        ),
    ]
