# Generated by Django 4.1 on 2022-08-12 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rpi", "0004_alter_raspberrypi_ip_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="raspberrypiurls",
            options={"verbose_name_plural": "raspberrypiurls"},
        ),
        migrations.RemoveField(
            model_name="raspberrypi",
            name="checked_in",
        ),
        migrations.RemoveField(
            model_name="raspberrypi",
            name="connect",
        ),
        migrations.RemoveField(
            model_name="raspberrypi",
            name="date_deployed",
        ),
        migrations.RemoveField(
            model_name="raspberrypi",
            name="location",
        ),
        migrations.CreateModel(
            name="RaspberryPiDeployed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_deployed", models.DateTimeField(auto_now_add=True)),
                ("checked_in", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("connect", models.BooleanField(default=False)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rpi.location"
                    ),
                ),
                (
                    "rpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rpi.raspberrypi",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "raspberrypideployed",
            },
        ),
    ]
